### ISSUE TITLE
Change the way Cyberware upgrades are handled.

### ISSUE THREAD

**Issue by EtherealOnyx** [breakinblocks/nutsandbolts#135]
I was looking at the Cyberware mod, and I thought it was great. However, it seemed both limiting and powerful, and thought it could go with some changes to fit into this modpack properly.  The overall idea was to create a way to make you be able to use more upgrades, but also to increase the time it takes to create these items.

Suggested Changes:
- [ ] Add a complex recipe for the Robosurgeon, and remove it from Nether Fortresses if possible.
- [ ] Add recipes to specific blueprints, which can be made with NBT data on recipe outputs. Could be crafting recipes with unique items depending on the upgrade, or could be made with other machines.
- [ ] Disable scanners. (It would override the suggested recipes above).
- [ ] Add crafting recipes to Cyberware crafting ingredients (Solid-State Circuitry, Fibre Optics, etc).
- [ ] Remove Neuropozyne(?) from loot chests.
- [ ] Disable the Radial Broadcaster, Radio Kit, and the Radio beacon because they are useless.
- [ ] Add upgrades to dungeon loot, the better the more rare the upgrade. (An alternative to those who like exploring.)
- [x] Get rid of salvaged versions by not letting the items drop from CyberZombies, or disable CyberZombies. #134
- [x] Disable blueprints from Scanners.  #134
- [x] Disable "rejection". Reason simply because it's a potion effect, for 20 minutes. #134
- [x] Increase the chance of a blueprint from Engineering table, for those who wish to salvage a blueprint from an upgrade part found as loot. #134
- [x] Increase the tolerance limit. #134
- [x] Increase the power ratio of RF to Cyberpower to 5 from 1. #134
- [x] Make Cyberware drop on death, instead of magically disappear. #134

Possible Conflicts:
-Makes CyberZombies nothing aside from a mob that increases health.
-Could potentially make the Engineer Workshop less useful.
-Removes Neuropozyne(?) which imitates an overflow mechanic of a sort.

Suggested Solutions:
-Infernal mobs, Rough Mobs, and Cyber Zombie group-spawn increased. Need I say more?
-If upgrade pieces are added to dungeon loot, the Engineer Workshop could be vital in creating blueprints for those explorer-type people. It would still not be completely useless.
-I personally think Neuropozyne(?) was a terrible idea and mechanic, the fact that you have to "inject" (instantly eat) a shot every 20 minutes is not as great as it seems.

By doing this I believe it will change some of the ideas originally planned with Cyberware, but in the end, this will add more abilities along with proper balance, all which leads to another mod benefiting from end-game.
